### ISSUE TITLE
Pandas deprecation FutureWarning for .append 

### ISSUE THREAD

**Issue by dcnadler** [JuBiotech/bletl#16]
When I use `bldata.get_narrow_data()` I get the following warning:
```bash
/usr/local/lib/python3.8/dist-packages/bletl/types.py:84: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  narrow = narrow.append(to_add, sort=False)
```
pandas==1.4.1
bletl==1.1.0

Thanks! Great package!

**Comment by michaelosthege** [comment]
Thanks for the reminder! I guess the append should be replaced by collecting data in a dict of lists and creating the dataframe afterwards.
If you want to contribute that change please go ahead!
I can't predict when someone from our side will find the time to do it.
